# === Server ===
server.port=${SERVER_PORT:8080}

spring.application.name=${SPRING_APPLICATION_NAME:Rewards API}

# === H2 Database Config ===
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:rewardsdb}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# === JPA Config ===
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

# === Enable H2 Console ===
spring.h2.console.enabled=${SPRING_H2_CONSOLE_ENABLED:true}
spring.h2.console.path=${SPRING_H2_CONSOLE_PATH:/h2-console}

# === SQL Init Mode (for data.sql) ===
spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}

# === Actuator ===
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}

# === Logging ===
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
logging.level.com.assessment.rewards=${LOGGING_LEVEL_COM_ASSESSMENT_REWARDS:DEBUG}

